### PR TITLE
Complete upgrade to PlatformIO

### PR DESCRIPTION
**Pull request by kotl**
Includes two configurations for V1_ILI9488 and Makerfabs

### CODE REVIEW

**Comment by DustinWatts** [comment]
Wow! @kotl I was struggling to do this myself (not a PlatformIO user at all) but this looks great! I'll check later if I can get this to work over here, but maybe it is an idea to make a separate branch for PlatformIO?

**Comment by kotl** [comment]
I would not recommend that (separate branch) since it would be a bit of a nightmare to merge changes back and forth given the files have to be in different directories. It's pretty much all-in or not. Given how many dependencies your project has (including custom library), I would just go all-in for platformio since it literally is a single click to compile and upload data folder. What you probably need to add is some README changes to explain what happened.

**Comment by tubalainen** [comment]
HALLELULIA!!!! :)

Me and Arduino IDE will NEVER get along well, its such as mess on so many levels.

Managed to get it all working via PlatformIO/VSCode thank your a billion @kotl !! <3
image

**Comment by tubalainen** [comment]
@kotl may I suggest adding https://github.com/DustinWatts/FT6236 as well to the `lib_deps_external =`

```
[common_env_data]
lib_deps_external = 
```

Thanks :)

**Comment by tubalainen** [comment]
> Wow! @kotl I was struggling to do this myself (not a PlatformIO user at all) but this looks great! I'll check later if I can get this to work over here, but maybe it is an idea to make a separate branch for PlatformIO?

Download the zipfile from gihub, unzip.
No configs needed such as adding libs manually - just install VSCode och PlatformIO - "open folder" and navigate to the folder where platformio.ini is located, make the adjustments accordingly, compile and "Bobs your uncle"!

**Comment by fietser28** [comment]
Just created a new PR (#63) that still allows for Arduino IDE builds. Hopefully that will make it easier for people unfamiliar with platformio.
Used much of the original work of @kotl in the new PR.

**Pull request closed without merging**
