### PR TITLE
Added GT911 touchscreen support and added support for ESP32-3248S035 Capacitive and ESP32-2432S028 Resistive

### PR DESCRIPTION
**Pull request by Raycast7373**
the only problem currently is that you cant see the current config/ínformation thing cuz it somehow closes it as soon as it shows which currently is temporarily fixed using a 3 second delay

### CODE REVIEW

**Comment by DustinWatts** [comment]
Hi @Raycast7373 Thanks for this PR. I do not have a GT911 myself so I can't be of any assistance I think regarding the issues you mentioned. I will look over the changes in the code and if everything turns out to be good to go I will merge! Thanks again!

**Comment by Raycast7373** [comment]
👍👍

**Comment by Raycast7373** [comment]
Adding a 3 second delay to the info page works good enough in most cases i guess (worked good enough for me)

#ifdef gt911
 delay(3000);
#endif

**Comment by Raycast7373** [comment]
The wake on touch thing seems to not work with the gt911
You can theoretically fix it by always looking for if the touch screen is touched instead of the gpio interrupt thing (haven't looked into how it normally functions tho)

**Comment by DustinWatts** [comment]
> The wake on touch thing seems to not work with the gt911 You can theoretically fix it by always looking for if the touch screen is touched instead of the gpio interrupt thing (haven't looked into how it normally functions tho)

I'll have a look at the datasheet and the library. You could also check with a multimeter or oscilloscope (if you have one) what happens one that pin when you touch the screen. Also maybe there is an example in the library showing how to use the interrupt...

**Comment by Raycast7373** [comment]
backlight control works after changing a small bit of code

**Comment by DustinWatts** [comment]
Could you make it so that, everything you need for the GT911 is between #IFDEF's and the default still is the "normal" version for the ESP32 with resistive touchscreen?

**Comment by Raycast7373** [comment]
gonna work on it now
i cant test it out right now tho cuz i left my esp32 board at home

**Comment by Raycast7373** [comment]
should be good now

**Comment by DustinWatts** [comment]
The compile test fails. Changed the compile.yaml but somehow it still uses the old .yaml. Even though the correct changes are visible in the .yaml file. Maybe it takes a while for it to use the updated one. Will try again tomorrow. I want it to ignore warnings for now and only fail on errors.

**Comment by DustinWatts** [comment]
Well... it seems for now I can't figure out how to do this in the .yaml. I can't change -all to -error. I will do this manually and ignore this fail for now.

**Comment by Raycast7373** [comment]
- Added support for ESP32-2432S028 (320x280) Resistive as it didnt work on the resistive touch thingy even tho it uses a XPT2046 touchscreen
- Rewrote the touchscreen part, now uses a function instead of just having the same code multiple times which makes porting FreeTouchDeck a bit easier
- You now need to uncomment something to make it work with resistive touch as it will otherwise make stuff harder the more devices it supports

To-Do:
- add XPT2046 calibration tool thingy (ESP32-2432S028, XPT2046)
- add light sensor calibration tool thingy (ESP32-2432S028, ESP32-3248S035)

**Comment by DustinWatts** [comment]
Only hardware that is on the Supported Hardware will be reflected in the code. PR's that add support for other boards will not be accepted. You can off course point people to your fork. 

For me it is not doable to add support for all kinds of boards. Especially if I do not have the board myself.

**Pull request closed without merging**
